.TH CSSDUPS 1 "2011-01-13" "rlp1938@gmail.com" "Linux User's Manual"

.SH NAME
cssdups \- a program to report on duplicated style names in a CSS or
HTML file, and optionally list empty lines by line number.

.SH SYNOPSIS
.B cssdups
.RI [ options ] " cssfile"
.br

.SH DESCRIPTION
The program examines the user named CSS or HTML file and reports
duplicated style names. Some such styles may replicated harmlessly
eg '@font-family' but other styles may harm the way the html using the
CSS renders in the browser, eg div.big is one that may be problematic if
duplicated. It is possible to block reporting of harmless duplications.
This may be done by editing \fI$HOME/.config/cssdups/csdexcl.\fR That
file is installed automatically when the program is first run.

.SH OPTIONS
.IP \fB\-h\f
prints helpfile.
.IP \fB\-e\f
Lists empty lines by line number.

.SH NOTES
Be certain that anything you add to the csdexcl file is really
harmless when duplicated in the CSS, because once inserted that object
will never again be reported as a duplicate. If a mistaken entry must be
removed you can do it in any text editor.
.P
Note that for HTML files the duplicate search is confined to the style
tags contained within the head tags. Individual styles attached to html
elements are not examined.
